<?php
namespace controllers\crud\viewers;

use Ajax\semantic\html\elements\HtmlLabel;
use Ajax\semantic\widgets\datatable\PositionInTable;
use Ubiquity\controllers\crud\viewers\ModelViewer;
use Ubiquity\utils\http\USession;

/**
  * Class CrudUsersViewer
  */
class CrudUsersViewer extends ModelViewer{
	private $letters=[];
	public function getCaptions($captions, $className) {
		return ['','Prénom','Nom','Email','Suspendu ?','Groupes'];
	}

	public function isModal($objects, $model) {
		return false;
	}

	public function getModelDataTable($instances, $model, $totalCount, $page = 1) {
		$res= parent::getModelDataTable($instances, $model, $totalCount, $page);
		$this->updateWidgetFields($res);
		$res->setValueFunction('letter',function($v,$instance){
			$letter=substr($instance->getLastname(),0,1);
			$this->letters[$letter]="a:contains($letter)";
			return '<h3 id="'.$letter.'">'.$letter.'</h3>';
		});
		$res->addButtonsInToolbar( range('A', 'Z'),false,function($elm){
			$items=$elm->getItems();
			foreach ($items as $item) {
				$item->addClass('black');
				$item->setProperty('style', 'display:none;');
				$item->setTagName('a')->setProperty('href','#'.$item->getContent());
			}
		})->getContent()->addClass('mini');
		$res->setToolbarPosition([PositionInTable::HEADER,PositionInTable::FOOTER]);
		$res->onPostCompile(function(){
			$this->controller->jquery->show(\implode(',',$this->letters),'','',true);
		});

		return $res;
	}

	private function updateWidgetFields($widget){
		$widget->fieldAsCheckbox('suspended');
		$widget->setValueFunction('groups',function($value,$instance){
			$result=[];
			$groupes=$instance->getGroups();
			if(is_array($groupes)) {
				foreach ($groupes as $groupe) {
					$lbl = new HtmlLabel('grp-' . $groupe->getId(), $groupe);
					$lbl->addIcon('people arrows');
					$lbl->addClass('basic inverted');
					$result[] = $lbl;
				}
			}
			return $result;
		});
	}

	public function getModelDataElement($instance, $model, $modal) {
		$res= parent::getModelDataElement($instance, $model, $modal);
		$this->updateWidgetFields($res);
		return $res;
	}

	public function recordsPerPage($model, $totalCount = 0) {
		return $totalCount;
	}

	protected function getDataTableRowButtons() {
		return [ 'display','edit','delete' ];
	}

	public function getForm($identifier, $instance, $updateUrl = 'updateModel') {
		$res=parent::getForm($identifier,$instance,$updateUrl);
		$res->fieldAsHidden('id');
		$res->fieldAsHidden('idOrganization');
		return $res;
	}

	public function getFormCaptions($captions, $className, $instance) {
		return ['','Prénom','Nom','Email','Suspendu ?','Groupes'];
	}

	public function getElementCaptions($captions, $className, $instance) {
		return parent::getElementCaptions($captions, $className, $instance); // TODO: Change the autogenerated stub
	}

	public function getGroupByFields() {
		return [0]; // TODO: Change the autogenerated stub
	}


}
